/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type {
  DataStore,
  DeleteApiV1DataStoreLabelsParams,
  DeleteApiV1DataStoreParams,
  DeleteApiV1ServiceTemplateRemoveParams,
  GetApiV1DataStoreParams,
  GetApiV1ServiceCatalogDownloadParams,
  GetApiV1ServiceCatalogInstructionsParams,
  GetApiV1ServiceCatalogParams,
  GetApiV1ServiceTemplateDownloadParams,
  GetApiV1ServiceTemplateGetParams,
  GetApiV1ServiceTemplateListParams,
  GetApiV1ServiceTemplatePropertiesParams,
  TemplateInstantiationRequest,
  WanakuResponseDataStore,
  WanakuResponseDeploymentInstructions,
  WanakuResponseInteger,
  WanakuResponseListDataStore,
  WanakuResponseListMapStringObject,
  WanakuResponseListServiceTemplateSummary,
  WanakuResponseMapStringMapStringString,
  WanakuResponseMapStringObject,
  WanakuResponseServerInfo,
  WanakuResponseServiceTemplateDetail,
  WanakuResponseSystemStatistics,
  WanakuResponseVoid,
} from "../models";

import { customFetch } from "../custom-fetch";
/**
 * @summary Update
 */
export type putApiV1DataStoreResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type putApiV1DataStoreResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1DataStoreResponseSuccess = putApiV1DataStoreResponse200 & {
  headers: Headers;
};
export type putApiV1DataStoreResponseError = putApiV1DataStoreResponse400 & {
  headers: Headers;
};

export type putApiV1DataStoreResponse =
  | putApiV1DataStoreResponseSuccess
  | putApiV1DataStoreResponseError;

export const getPutApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const putApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<putApiV1DataStoreResponse> => {
  return customFetch<putApiV1DataStoreResponse>(getPutApiV1DataStoreUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary Remove By Name
 */
export type deleteApiV1DataStoreResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1DataStoreResponseSuccess =
  deleteApiV1DataStoreResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreResponse = deleteApiV1DataStoreResponseSuccess;

export const getDeleteApiV1DataStoreUrl = (
  params?: DeleteApiV1DataStoreParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const deleteApiV1DataStore = async (
  params?: DeleteApiV1DataStoreParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreResponse> => {
  return customFetch<deleteApiV1DataStoreResponse>(
    getDeleteApiV1DataStoreUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List Or Get By Name
 */
export type getApiV1DataStoreResponse200 = {
  data: WanakuResponseListDataStore;
  status: 200;
};

export type getApiV1DataStoreResponseSuccess = getApiV1DataStoreResponse200 & {
  headers: Headers;
};
export type getApiV1DataStoreResponse = getApiV1DataStoreResponseSuccess;

export const getGetApiV1DataStoreUrl = (params?: GetApiV1DataStoreParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const getApiV1DataStore = async (
  params?: GetApiV1DataStoreParams,
  options?: RequestInit,
): Promise<getApiV1DataStoreResponse> => {
  return customFetch<getApiV1DataStoreResponse>(
    getGetApiV1DataStoreUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Add
 */
export type postApiV1DataStoreResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1DataStoreResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1DataStoreResponseSuccess =
  postApiV1DataStoreResponse200 & {
    headers: Headers;
  };
export type postApiV1DataStoreResponseError = postApiV1DataStoreResponse400 & {
  headers: Headers;
};

export type postApiV1DataStoreResponse =
  | postApiV1DataStoreResponseSuccess
  | postApiV1DataStoreResponseError;

export const getPostApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const postApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1DataStoreResponse> => {
  return customFetch<postApiV1DataStoreResponse>(getPostApiV1DataStoreUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary Remove If
 */
export type deleteApiV1DataStoreLabelsResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1DataStoreLabelsResponseSuccess =
  deleteApiV1DataStoreLabelsResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreLabelsResponse =
  deleteApiV1DataStoreLabelsResponseSuccess;

export const getDeleteApiV1DataStoreLabelsUrl = (
  params?: DeleteApiV1DataStoreLabelsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/labels?${stringifiedParams}`
    : `/api/v1/data-store/labels`;
};

export const deleteApiV1DataStoreLabels = async (
  params?: DeleteApiV1DataStoreLabelsParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreLabelsResponse> => {
  return customFetch<deleteApiV1DataStoreLabelsResponse>(
    getDeleteApiV1DataStoreLabelsUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Remove By Id
 */
export type deleteApiV1DataStoreIdResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1DataStoreIdResponseSuccess =
  deleteApiV1DataStoreIdResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreIdResponse =
  deleteApiV1DataStoreIdResponseSuccess;

export const getDeleteApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const deleteApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreIdResponse> => {
  return customFetch<deleteApiV1DataStoreIdResponse>(
    getDeleteApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Id
 */
export type getApiV1DataStoreIdResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1DataStoreIdResponseSuccess =
  getApiV1DataStoreIdResponse200 & {
    headers: Headers;
  };
export type getApiV1DataStoreIdResponse = getApiV1DataStoreIdResponseSuccess;

export const getGetApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const getApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1DataStoreIdResponse> => {
  return customFetch<getApiV1DataStoreIdResponse>(
    getGetApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ManagementInfoVersionResponse200 = {
  data: WanakuResponseServerInfo;
  status: 200;
};

export type getApiV1ManagementInfoVersionResponseSuccess =
  getApiV1ManagementInfoVersionResponse200 & {
    headers: Headers;
  };
export type getApiV1ManagementInfoVersionResponse =
  getApiV1ManagementInfoVersionResponseSuccess;

export const getGetApiV1ManagementInfoVersionUrl = () => {
  return `/api/v1/management/info/version`;
};

export const getApiV1ManagementInfoVersion = async (
  options?: RequestInit,
): Promise<getApiV1ManagementInfoVersionResponse> => {
  return customFetch<getApiV1ManagementInfoVersionResponse>(
    getGetApiV1ManagementInfoVersionUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Statistics
 */
export type getApiV1ManagementStatisticsResponse200 = {
  data: WanakuResponseSystemStatistics;
  status: 200;
};

export type getApiV1ManagementStatisticsResponseSuccess =
  getApiV1ManagementStatisticsResponse200 & {
    headers: Headers;
  };
export type getApiV1ManagementStatisticsResponse =
  getApiV1ManagementStatisticsResponseSuccess;

export const getGetApiV1ManagementStatisticsUrl = () => {
  return `/api/v1/management/statistics`;
};

export const getApiV1ManagementStatistics = async (
  options?: RequestInit,
): Promise<getApiV1ManagementStatisticsResponse> => {
  return customFetch<getApiV1ManagementStatisticsResponse>(
    getGetApiV1ManagementStatisticsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ServiceCatalogResponse200 = {
  data: WanakuResponseListMapStringObject;
  status: 200;
};

export type getApiV1ServiceCatalogResponseSuccess =
  getApiV1ServiceCatalogResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogResponse =
  getApiV1ServiceCatalogResponseSuccess;

export const getGetApiV1ServiceCatalogUrl = (
  params?: GetApiV1ServiceCatalogParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog?${stringifiedParams}`
    : `/api/v1/service-catalog`;
};

export const getApiV1ServiceCatalog = async (
  params?: GetApiV1ServiceCatalogParams,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogResponse> => {
  return customFetch<getApiV1ServiceCatalogResponse>(
    getGetApiV1ServiceCatalogUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deploy
 */
export type postApiV1ServiceCatalogResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceCatalogResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceCatalogResponseSuccess =
  postApiV1ServiceCatalogResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceCatalogResponseError =
  postApiV1ServiceCatalogResponse400 & {
    headers: Headers;
  };

export type postApiV1ServiceCatalogResponse =
  | postApiV1ServiceCatalogResponseSuccess
  | postApiV1ServiceCatalogResponseError;

export const getPostApiV1ServiceCatalogUrl = () => {
  return `/api/v1/service-catalog`;
};

export const postApiV1ServiceCatalog = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1ServiceCatalogResponse> => {
  return customFetch<postApiV1ServiceCatalogResponse>(
    getPostApiV1ServiceCatalogUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Download
 */
export type getApiV1ServiceCatalogDownloadResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1ServiceCatalogDownloadResponseSuccess =
  getApiV1ServiceCatalogDownloadResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogDownloadResponse =
  getApiV1ServiceCatalogDownloadResponseSuccess;

export const getGetApiV1ServiceCatalogDownloadUrl = (
  params?: GetApiV1ServiceCatalogDownloadParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog/download?${stringifiedParams}`
    : `/api/v1/service-catalog/download`;
};

export const getApiV1ServiceCatalogDownload = async (
  params?: GetApiV1ServiceCatalogDownloadParams,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogDownloadResponse> => {
  return customFetch<getApiV1ServiceCatalogDownloadResponse>(
    getGetApiV1ServiceCatalogDownloadUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Deployment Instructions
 */
export type getApiV1ServiceCatalogInstructionsResponse200 = {
  data: WanakuResponseDeploymentInstructions;
  status: 200;
};

export type getApiV1ServiceCatalogInstructionsResponseSuccess =
  getApiV1ServiceCatalogInstructionsResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogInstructionsResponse =
  getApiV1ServiceCatalogInstructionsResponseSuccess;

export const getGetApiV1ServiceCatalogInstructionsUrl = (
  params?: GetApiV1ServiceCatalogInstructionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog/instructions?${stringifiedParams}`
    : `/api/v1/service-catalog/instructions`;
};

export const getApiV1ServiceCatalogInstructions = async (
  params?: GetApiV1ServiceCatalogInstructionsParams,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogInstructionsResponse> => {
  return customFetch<getApiV1ServiceCatalogInstructionsResponse>(
    getGetApiV1ServiceCatalogInstructionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ServiceCatalogNameResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1ServiceCatalogNameResponseSuccess =
  deleteApiV1ServiceCatalogNameResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ServiceCatalogNameResponse =
  deleteApiV1ServiceCatalogNameResponseSuccess;

export const getDeleteApiV1ServiceCatalogNameUrl = (name: string) => {
  return `/api/v1/service-catalog/${name}`;
};

export const deleteApiV1ServiceCatalogName = async (
  name: string,
  options?: RequestInit,
): Promise<deleteApiV1ServiceCatalogNameResponse> => {
  return customFetch<deleteApiV1ServiceCatalogNameResponse>(
    getDeleteApiV1ServiceCatalogNameUrl(name),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get
 */
export type getApiV1ServiceCatalogNameResponse200 = {
  data: WanakuResponseMapStringObject;
  status: 200;
};

export type getApiV1ServiceCatalogNameResponseSuccess =
  getApiV1ServiceCatalogNameResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogNameResponse =
  getApiV1ServiceCatalogNameResponseSuccess;

export const getGetApiV1ServiceCatalogNameUrl = (name: string) => {
  return `/api/v1/service-catalog/${name}`;
};

export const getApiV1ServiceCatalogName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogNameResponse> => {
  return customFetch<getApiV1ServiceCatalogNameResponse>(
    getGetApiV1ServiceCatalogNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deploy
 */
export type postApiV1ServiceTemplateDeployResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceTemplateDeployResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceTemplateDeployResponseSuccess =
  postApiV1ServiceTemplateDeployResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateDeployResponseError =
  postApiV1ServiceTemplateDeployResponse400 & {
    headers: Headers;
  };

export type postApiV1ServiceTemplateDeployResponse =
  | postApiV1ServiceTemplateDeployResponseSuccess
  | postApiV1ServiceTemplateDeployResponseError;

export const getPostApiV1ServiceTemplateDeployUrl = () => {
  return `/api/v1/service-template/deploy`;
};

export const postApiV1ServiceTemplateDeploy = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateDeployResponse> => {
  return customFetch<postApiV1ServiceTemplateDeployResponse>(
    getPostApiV1ServiceTemplateDeployUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Download
 */
export type getApiV1ServiceTemplateDownloadResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1ServiceTemplateDownloadResponseSuccess =
  getApiV1ServiceTemplateDownloadResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateDownloadResponse =
  getApiV1ServiceTemplateDownloadResponseSuccess;

export const getGetApiV1ServiceTemplateDownloadUrl = (
  params?: GetApiV1ServiceTemplateDownloadParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/download?${stringifiedParams}`
    : `/api/v1/service-template/download`;
};

export const getApiV1ServiceTemplateDownload = async (
  params?: GetApiV1ServiceTemplateDownloadParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateDownloadResponse> => {
  return customFetch<getApiV1ServiceTemplateDownloadResponse>(
    getGetApiV1ServiceTemplateDownloadUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get
 */
export type getApiV1ServiceTemplateGetResponse200 = {
  data: WanakuResponseServiceTemplateDetail;
  status: 200;
};

export type getApiV1ServiceTemplateGetResponseSuccess =
  getApiV1ServiceTemplateGetResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateGetResponse =
  getApiV1ServiceTemplateGetResponseSuccess;

export const getGetApiV1ServiceTemplateGetUrl = (
  params?: GetApiV1ServiceTemplateGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/get?${stringifiedParams}`
    : `/api/v1/service-template/get`;
};

export const getApiV1ServiceTemplateGet = async (
  params?: GetApiV1ServiceTemplateGetParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateGetResponse> => {
  return customFetch<getApiV1ServiceTemplateGetResponse>(
    getGetApiV1ServiceTemplateGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Instantiate
 */
export type postApiV1ServiceTemplateInstantiateResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceTemplateInstantiateResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceTemplateInstantiateResponseSuccess =
  postApiV1ServiceTemplateInstantiateResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateInstantiateResponseError =
  postApiV1ServiceTemplateInstantiateResponse400 & {
    headers: Headers;
  };

export type postApiV1ServiceTemplateInstantiateResponse =
  | postApiV1ServiceTemplateInstantiateResponseSuccess
  | postApiV1ServiceTemplateInstantiateResponseError;

export const getPostApiV1ServiceTemplateInstantiateUrl = () => {
  return `/api/v1/service-template/instantiate`;
};

export const postApiV1ServiceTemplateInstantiate = async (
  templateInstantiationRequest: TemplateInstantiationRequest,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateInstantiateResponse> => {
  return customFetch<postApiV1ServiceTemplateInstantiateResponse>(
    getPostApiV1ServiceTemplateInstantiateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(templateInstantiationRequest),
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ServiceTemplateListResponse200 = {
  data: WanakuResponseListServiceTemplateSummary;
  status: 200;
};

export type getApiV1ServiceTemplateListResponseSuccess =
  getApiV1ServiceTemplateListResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateListResponse =
  getApiV1ServiceTemplateListResponseSuccess;

export const getGetApiV1ServiceTemplateListUrl = (
  params?: GetApiV1ServiceTemplateListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/list?${stringifiedParams}`
    : `/api/v1/service-template/list`;
};

export const getApiV1ServiceTemplateList = async (
  params?: GetApiV1ServiceTemplateListParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateListResponse> => {
  return customFetch<getApiV1ServiceTemplateListResponse>(
    getGetApiV1ServiceTemplateListUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Properties
 */
export type getApiV1ServiceTemplatePropertiesResponse200 = {
  data: WanakuResponseMapStringMapStringString;
  status: 200;
};

export type getApiV1ServiceTemplatePropertiesResponseSuccess =
  getApiV1ServiceTemplatePropertiesResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplatePropertiesResponse =
  getApiV1ServiceTemplatePropertiesResponseSuccess;

export const getGetApiV1ServiceTemplatePropertiesUrl = (
  params?: GetApiV1ServiceTemplatePropertiesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/properties?${stringifiedParams}`
    : `/api/v1/service-template/properties`;
};

export const getApiV1ServiceTemplateProperties = async (
  params?: GetApiV1ServiceTemplatePropertiesParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplatePropertiesResponse> => {
  return customFetch<getApiV1ServiceTemplatePropertiesResponse>(
    getGetApiV1ServiceTemplatePropertiesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ServiceTemplateRemoveResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1ServiceTemplateRemoveResponseSuccess =
  deleteApiV1ServiceTemplateRemoveResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ServiceTemplateRemoveResponse =
  deleteApiV1ServiceTemplateRemoveResponseSuccess;

export const getDeleteApiV1ServiceTemplateRemoveUrl = (
  params?: DeleteApiV1ServiceTemplateRemoveParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/remove?${stringifiedParams}`
    : `/api/v1/service-template/remove`;
};

export const deleteApiV1ServiceTemplateRemove = async (
  params?: DeleteApiV1ServiceTemplateRemoveParams,
  options?: RequestInit,
): Promise<deleteApiV1ServiceTemplateRemoveResponse> => {
  return customFetch<deleteApiV1ServiceTemplateRemoveResponse>(
    getDeleteApiV1ServiceTemplateRemoveUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};
