/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type {
  DataStore,
  DeleteApiV1DataStoreIdParams,
  DeleteApiV1DataStoreLabelsParams,
  DeleteApiV1DataStoreParams,
  DeleteApiV1ServiceTemplateRemoveParams,
  GetApiV1AuditEventsParams,
  GetApiV1DataStoreParams,
  GetApiV1KameletsNameKameletYamlParams,
  GetApiV1KameletsNameParams,
  GetApiV1SemanticRoutersActionsParams,
  GetApiV1SemanticRoutersResolveParams,
  GetApiV1ServiceCatalogDownloadParams,
  GetApiV1ServiceCatalogInstructionsParams,
  GetApiV1ServiceCatalogParams,
  GetApiV1ServiceTemplateDownloadParams,
  GetApiV1ServiceTemplateGetParams,
  GetApiV1ServiceTemplateListParams,
  GetApiV1ServiceTemplatePropertiesParams,
  GetApiV1ServiceTemplateVersionsDownloadParams,
  GetApiV1ServiceTemplateVersionsGetParams,
  GetApiV1ServiceTemplateVersionsParams,
  KameletUpload,
  PostApiV1ServiceCatalogNameVersionsVersionActivateParams,
  PostApiV1ServiceCatalogParams,
  PostApiV1ServiceTemplateDeployParams,
  PostApiV1ServiceTemplateRestoreParams,
  PostApiV1ServiceTemplateVersionsActivateParams,
  PutApiV1DataStoreParams,
  SemanticPreviewRequest,
  SemanticRouterDefinition,
  TemplateInstantiationRequest,
  WanakuResponseAuditEvent,
  WanakuResponseAuditHealth,
  WanakuResponseAuditPage,
  WanakuResponseCatalogVersion,
  WanakuResponseDataStore,
  WanakuResponseDataStoreRecord,
  WanakuResponseDeploymentInstructions,
  WanakuResponseInteger,
  WanakuResponseKameletDefinition,
  WanakuResponseKameletSummary,
  WanakuResponseListCatalogVersion,
  WanakuResponseListDataStoreRecord,
  WanakuResponseListKameletSummary,
  WanakuResponseListMapStringObject,
  WanakuResponseListSemanticAction,
  WanakuResponseListSemanticExpert,
  WanakuResponseListSemanticPublication,
  WanakuResponseListSemanticRouterDefinition,
  WanakuResponseListServiceTemplateSummary,
  WanakuResponseMapStringMapStringString,
  WanakuResponseMapStringObject,
  WanakuResponseMapStringString,
  WanakuResponseSemanticPreview,
  WanakuResponseSemanticPublication,
  WanakuResponseSemanticResolvedPublication,
  WanakuResponseSemanticRouterDefinition,
  WanakuResponseSemanticValidation,
  WanakuResponseServerInfo,
  WanakuResponseServiceTemplateDetail,
  WanakuResponseSystemStatistics,
  WanakuResponseValidationResult,
  WanakuResponseVoid,
} from "../models";

import { customFetch } from "../custom-fetch";
/**
 * @summary List
 */
export type getApiV1AuditEventsResponse200 = {
  data: WanakuResponseAuditPage;
  status: 200;
};

export type getApiV1AuditEventsResponseSuccess =
  getApiV1AuditEventsResponse200 & {
    headers: Headers;
  };
export type getApiV1AuditEventsResponse = getApiV1AuditEventsResponseSuccess;

export const getGetApiV1AuditEventsUrl = (
  params?: GetApiV1AuditEventsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/audit/events?${stringifiedParams}`
    : `/api/v1/audit/events`;
};

export const getApiV1AuditEvents = async (
  params?: GetApiV1AuditEventsParams,
  options?: RequestInit,
): Promise<getApiV1AuditEventsResponse> => {
  return customFetch<getApiV1AuditEventsResponse>(
    getGetApiV1AuditEventsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get
 */
export type getApiV1AuditEventsIdResponse200 = {
  data: WanakuResponseAuditEvent;
  status: 200;
};

export type getApiV1AuditEventsIdResponseSuccess =
  getApiV1AuditEventsIdResponse200 & {
    headers: Headers;
  };
export type getApiV1AuditEventsIdResponse =
  getApiV1AuditEventsIdResponseSuccess;

export const getGetApiV1AuditEventsIdUrl = (id: string) => {
  return `/api/v1/audit/events/${id}`;
};

export const getApiV1AuditEventsId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1AuditEventsIdResponse> => {
  return customFetch<getApiV1AuditEventsIdResponse>(
    getGetApiV1AuditEventsIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Health
 */
export type getApiV1AuditHealthResponse200 = {
  data: WanakuResponseAuditHealth;
  status: 200;
};

export type getApiV1AuditHealthResponseSuccess =
  getApiV1AuditHealthResponse200 & {
    headers: Headers;
  };
export type getApiV1AuditHealthResponse = getApiV1AuditHealthResponseSuccess;

export const getGetApiV1AuditHealthUrl = () => {
  return `/api/v1/audit/health`;
};

export const getApiV1AuditHealth = async (
  options?: RequestInit,
): Promise<getApiV1AuditHealthResponse> => {
  return customFetch<getApiV1AuditHealthResponse>(getGetApiV1AuditHealthUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Schema
 */
export type getApiV1AuditSchemaResponse200 = {
  data: WanakuResponseMapStringString;
  status: 200;
};

export type getApiV1AuditSchemaResponseSuccess =
  getApiV1AuditSchemaResponse200 & {
    headers: Headers;
  };
export type getApiV1AuditSchemaResponse = getApiV1AuditSchemaResponseSuccess;

export const getGetApiV1AuditSchemaUrl = () => {
  return `/api/v1/audit/schema`;
};

export const getApiV1AuditSchema = async (
  options?: RequestInit,
): Promise<getApiV1AuditSchemaResponse> => {
  return customFetch<getApiV1AuditSchemaResponse>(getGetApiV1AuditSchemaUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Update
 */
export type putApiV1DataStoreResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type putApiV1DataStoreResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1DataStoreResponseSuccess = putApiV1DataStoreResponse200 & {
  headers: Headers;
};
export type putApiV1DataStoreResponseError = putApiV1DataStoreResponse400 & {
  headers: Headers;
};

export type putApiV1DataStoreResponse =
  | putApiV1DataStoreResponseSuccess
  | putApiV1DataStoreResponseError;

export const getPutApiV1DataStoreUrl = (params?: PutApiV1DataStoreParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const putApiV1DataStore = async (
  dataStore: DataStore,
  params?: PutApiV1DataStoreParams,
  options?: RequestInit,
): Promise<putApiV1DataStoreResponse> => {
  return customFetch<putApiV1DataStoreResponse>(
    getPutApiV1DataStoreUrl(params),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Remove By Name
 */
export type deleteApiV1DataStoreResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1DataStoreResponseSuccess =
  deleteApiV1DataStoreResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreResponse = deleteApiV1DataStoreResponseSuccess;

export const getDeleteApiV1DataStoreUrl = (
  params?: DeleteApiV1DataStoreParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const deleteApiV1DataStore = async (
  params?: DeleteApiV1DataStoreParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreResponse> => {
  return customFetch<deleteApiV1DataStoreResponse>(
    getDeleteApiV1DataStoreUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary List Or Get By Name
 */
export type getApiV1DataStoreResponse200 = {
  data: WanakuResponseListDataStoreRecord;
  status: 200;
};

export type getApiV1DataStoreResponseSuccess = getApiV1DataStoreResponse200 & {
  headers: Headers;
};
export type getApiV1DataStoreResponse = getApiV1DataStoreResponseSuccess;

export const getGetApiV1DataStoreUrl = (params?: GetApiV1DataStoreParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store?${stringifiedParams}`
    : `/api/v1/data-store`;
};

export const getApiV1DataStore = async (
  params?: GetApiV1DataStoreParams,
  options?: RequestInit,
): Promise<getApiV1DataStoreResponse> => {
  return customFetch<getApiV1DataStoreResponse>(
    getGetApiV1DataStoreUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Add
 */
export type postApiV1DataStoreResponse200 = {
  data: WanakuResponseDataStoreRecord;
  status: 200;
};

export type postApiV1DataStoreResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1DataStoreResponseSuccess =
  postApiV1DataStoreResponse200 & {
    headers: Headers;
  };
export type postApiV1DataStoreResponseError = postApiV1DataStoreResponse400 & {
  headers: Headers;
};

export type postApiV1DataStoreResponse =
  | postApiV1DataStoreResponseSuccess
  | postApiV1DataStoreResponseError;

export const getPostApiV1DataStoreUrl = () => {
  return `/api/v1/data-store`;
};

export const postApiV1DataStore = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1DataStoreResponse> => {
  return customFetch<postApiV1DataStoreResponse>(getPostApiV1DataStoreUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(dataStore),
  });
};

/**
 * @summary Remove If
 */
export type deleteApiV1DataStoreLabelsResponse200 = {
  data: WanakuResponseInteger;
  status: 200;
};

export type deleteApiV1DataStoreLabelsResponseSuccess =
  deleteApiV1DataStoreLabelsResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreLabelsResponse =
  deleteApiV1DataStoreLabelsResponseSuccess;

export const getDeleteApiV1DataStoreLabelsUrl = (
  params?: DeleteApiV1DataStoreLabelsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/labels?${stringifiedParams}`
    : `/api/v1/data-store/labels`;
};

export const deleteApiV1DataStoreLabels = async (
  params?: DeleteApiV1DataStoreLabelsParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreLabelsResponse> => {
  return customFetch<deleteApiV1DataStoreLabelsResponse>(
    getDeleteApiV1DataStoreLabelsUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Remove By Id
 */
export type deleteApiV1DataStoreIdResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1DataStoreIdResponseSuccess =
  deleteApiV1DataStoreIdResponse200 & {
    headers: Headers;
  };
export type deleteApiV1DataStoreIdResponse =
  deleteApiV1DataStoreIdResponseSuccess;

export const getDeleteApiV1DataStoreIdUrl = (
  id: string,
  params?: DeleteApiV1DataStoreIdParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/data-store/${id}?${stringifiedParams}`
    : `/api/v1/data-store/${id}`;
};

export const deleteApiV1DataStoreId = async (
  id: string,
  params?: DeleteApiV1DataStoreIdParams,
  options?: RequestInit,
): Promise<deleteApiV1DataStoreIdResponse> => {
  return customFetch<deleteApiV1DataStoreIdResponse>(
    getDeleteApiV1DataStoreIdUrl(id, params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get By Id
 */
export type getApiV1DataStoreIdResponse200 = {
  data: WanakuResponseDataStoreRecord;
  status: 200;
};

export type getApiV1DataStoreIdResponseSuccess =
  getApiV1DataStoreIdResponse200 & {
    headers: Headers;
  };
export type getApiV1DataStoreIdResponse = getApiV1DataStoreIdResponseSuccess;

export const getGetApiV1DataStoreIdUrl = (id: string) => {
  return `/api/v1/data-store/${id}`;
};

export const getApiV1DataStoreId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1DataStoreIdResponse> => {
  return customFetch<getApiV1DataStoreIdResponse>(
    getGetApiV1DataStoreIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Validate and persist original YAML as an immutable SHA-256 revision. Select the uploaded revision for its name. Identical uploads are idempotent. This operation does not execute YAML or contact external services.
 * @summary Upload a Kamelet
 */
export type postApiV1KameletsResponse200 = {
  data: WanakuResponseKameletSummary;
  status: 200;
};

export type postApiV1KameletsResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1KameletsResponse409 = {
  data: void;
  status: 409;
};

export type postApiV1KameletsResponse422 = {
  data: void;
  status: 422;
};

export type postApiV1KameletsResponseSuccess = postApiV1KameletsResponse200 & {
  headers: Headers;
};
export type postApiV1KameletsResponseError = (
  | postApiV1KameletsResponse400
  | postApiV1KameletsResponse409
  | postApiV1KameletsResponse422
) & {
  headers: Headers;
};

export type postApiV1KameletsResponse =
  | postApiV1KameletsResponseSuccess
  | postApiV1KameletsResponseError;

export const getPostApiV1KameletsUrl = () => {
  return `/api/v1/kamelets`;
};

export const postApiV1Kamelets = async (
  kameletUpload: KameletUpload,
  options?: RequestInit,
): Promise<postApiV1KameletsResponse> => {
  return customFetch<postApiV1KameletsResponse>(getPostApiV1KameletsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(kameletUpload),
  });
};

/**
 * List native Kamelets and their semantic eligibility. Uploaded revisions are available immediately.
 * @summary List current Kamelets
 */
export type getApiV1KameletsResponse200 = {
  data: WanakuResponseListKameletSummary;
  status: 200;
};

export type getApiV1KameletsResponseSuccess = getApiV1KameletsResponse200 & {
  headers: Headers;
};
export type getApiV1KameletsResponse = getApiV1KameletsResponseSuccess;

export const getGetApiV1KameletsUrl = () => {
  return `/api/v1/kamelets`;
};

export const getApiV1Kamelets = async (
  options?: RequestInit,
): Promise<getApiV1KameletsResponse> => {
  return customFetch<getApiV1KameletsResponse>(getGetApiV1KameletsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * Remove an uploaded Kamelet from the current catalog. Retain immutable revisions for saved semantic routes. Bundled and configured definitions cannot be removed.
 * @summary Remove a current Kamelet selection
 */
export type deleteApiV1KameletsNameResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1KameletsNameResponse400 = {
  data: void;
  status: 400;
};

export type deleteApiV1KameletsNameResponse404 = {
  data: void;
  status: 404;
};

export type deleteApiV1KameletsNameResponse409 = {
  data: void;
  status: 409;
};

export type deleteApiV1KameletsNameResponseSuccess =
  deleteApiV1KameletsNameResponse200 & {
    headers: Headers;
  };
export type deleteApiV1KameletsNameResponseError = (
  | deleteApiV1KameletsNameResponse400
  | deleteApiV1KameletsNameResponse404
  | deleteApiV1KameletsNameResponse409
) & {
  headers: Headers;
};

export type deleteApiV1KameletsNameResponse =
  | deleteApiV1KameletsNameResponseSuccess
  | deleteApiV1KameletsNameResponseError;

export const getDeleteApiV1KameletsNameUrl = (name: string) => {
  return `/api/v1/kamelets/${name}`;
};

export const deleteApiV1KameletsName = async (
  name: string,
  options?: RequestInit,
): Promise<deleteApiV1KameletsNameResponse> => {
  return customFetch<deleteApiV1KameletsNameResponse>(
    getDeleteApiV1KameletsNameUrl(name),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Read the current definition or an exact immutable revision. Removed current selections do not remove retained revisions.
 * @summary Read a Kamelet
 */
export type getApiV1KameletsNameResponse200 = {
  data: WanakuResponseKameletDefinition;
  status: 200;
};

export type getApiV1KameletsNameResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1KameletsNameResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1KameletsNameResponseSuccess =
  getApiV1KameletsNameResponse200 & {
    headers: Headers;
  };
export type getApiV1KameletsNameResponseError = (
  | getApiV1KameletsNameResponse400
  | getApiV1KameletsNameResponse404
) & {
  headers: Headers;
};

export type getApiV1KameletsNameResponse =
  | getApiV1KameletsNameResponseSuccess
  | getApiV1KameletsNameResponseError;

export const getGetApiV1KameletsNameUrl = (
  name: string,
  params?: GetApiV1KameletsNameParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/kamelets/${name}?${stringifiedParams}`
    : `/api/v1/kamelets/${name}`;
};

export const getApiV1KameletsName = async (
  name: string,
  params?: GetApiV1KameletsNameParams,
  options?: RequestInit,
): Promise<getApiV1KameletsNameResponse> => {
  return customFetch<getApiV1KameletsNameResponse>(
    getGetApiV1KameletsNameUrl(name, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Return original UTF-8 YAML with a SHA-256 ETag. The filename path supports Camel Kamelet resource lookup.
 * @summary Download native Kamelet YAML
 */
export type getApiV1KameletsNameKameletYamlResponse200 = {
  data: string;
  status: 200;
};

export type getApiV1KameletsNameKameletYamlResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1KameletsNameKameletYamlResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1KameletsNameKameletYamlResponseSuccess =
  getApiV1KameletsNameKameletYamlResponse200 & {
    headers: Headers;
  };
export type getApiV1KameletsNameKameletYamlResponseError = (
  | getApiV1KameletsNameKameletYamlResponse400
  | getApiV1KameletsNameKameletYamlResponse404
) & {
  headers: Headers;
};

export type getApiV1KameletsNameKameletYamlResponse =
  | getApiV1KameletsNameKameletYamlResponseSuccess
  | getApiV1KameletsNameKameletYamlResponseError;

export const getGetApiV1KameletsNameKameletYamlUrl = (
  name: string,
  params?: GetApiV1KameletsNameKameletYamlParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/kamelets/${name}.kamelet.yaml?${stringifiedParams}`
    : `/api/v1/kamelets/${name}.kamelet.yaml`;
};

export const getApiV1KameletsNameKameletYaml = async (
  name: string,
  params?: GetApiV1KameletsNameKameletYamlParams,
  options?: RequestInit,
): Promise<getApiV1KameletsNameKameletYamlResponse> => {
  return customFetch<getApiV1KameletsNameKameletYamlResponse>(
    getGetApiV1KameletsNameKameletYamlUrl(name, params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ManagementInfoVersionResponse200 = {
  data: WanakuResponseServerInfo;
  status: 200;
};

export type getApiV1ManagementInfoVersionResponseSuccess =
  getApiV1ManagementInfoVersionResponse200 & {
    headers: Headers;
  };
export type getApiV1ManagementInfoVersionResponse =
  getApiV1ManagementInfoVersionResponseSuccess;

export const getGetApiV1ManagementInfoVersionUrl = () => {
  return `/api/v1/management/info/version`;
};

export const getApiV1ManagementInfoVersion = async (
  options?: RequestInit,
): Promise<getApiV1ManagementInfoVersionResponse> => {
  return customFetch<getApiV1ManagementInfoVersionResponse>(
    getGetApiV1ManagementInfoVersionUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Statistics
 */
export type getApiV1ManagementStatisticsResponse200 = {
  data: WanakuResponseSystemStatistics;
  status: 200;
};

export type getApiV1ManagementStatisticsResponseSuccess =
  getApiV1ManagementStatisticsResponse200 & {
    headers: Headers;
  };
export type getApiV1ManagementStatisticsResponse =
  getApiV1ManagementStatisticsResponseSuccess;

export const getGetApiV1ManagementStatisticsUrl = () => {
  return `/api/v1/management/statistics`;
};

export const getApiV1ManagementStatistics = async (
  options?: RequestInit,
): Promise<getApiV1ManagementStatisticsResponse> => {
  return customFetch<getApiV1ManagementStatisticsResponse>(
    getGetApiV1ManagementStatisticsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * List saved router drafts. Publication does not activate a runtime.
 * @summary List saved router drafts
 */
export type getApiV1SemanticRoutersResponse200 = {
  data: WanakuResponseListSemanticRouterDefinition;
  status: 200;
};

export type getApiV1SemanticRoutersResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1SemanticRoutersResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1SemanticRoutersResponseSuccess =
  getApiV1SemanticRoutersResponse200 & {
    headers: Headers;
  };
export type getApiV1SemanticRoutersResponseError = (
  | getApiV1SemanticRoutersResponse400
  | getApiV1SemanticRoutersResponse404
) & {
  headers: Headers;
};

export type getApiV1SemanticRoutersResponse =
  | getApiV1SemanticRoutersResponseSuccess
  | getApiV1SemanticRoutersResponseError;

export const getGetApiV1SemanticRoutersUrl = () => {
  return `/api/v1/semantic-routers`;
};

export const getApiV1SemanticRouters = async (
  options?: RequestInit,
): Promise<getApiV1SemanticRoutersResponse> => {
  return customFetch<getApiV1SemanticRoutersResponse>(
    getGetApiV1SemanticRoutersUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Save a router draft. Publication does not activate a runtime.
 * @summary Save a router draft
 */
export type postApiV1SemanticRoutersResponse200 = {
  data: WanakuResponseSemanticRouterDefinition;
  status: 200;
};

export type postApiV1SemanticRoutersResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1SemanticRoutersResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1SemanticRoutersResponseSuccess =
  postApiV1SemanticRoutersResponse200 & {
    headers: Headers;
  };
export type postApiV1SemanticRoutersResponseError = (
  | postApiV1SemanticRoutersResponse400
  | postApiV1SemanticRoutersResponse404
) & {
  headers: Headers;
};

export type postApiV1SemanticRoutersResponse =
  | postApiV1SemanticRoutersResponseSuccess
  | postApiV1SemanticRoutersResponseError;

export const getPostApiV1SemanticRoutersUrl = () => {
  return `/api/v1/semantic-routers`;
};

export const postApiV1SemanticRouters = async (
  semanticRouterDefinition: SemanticRouterDefinition,
  options?: RequestInit,
): Promise<postApiV1SemanticRoutersResponse> => {
  return customFetch<postApiV1SemanticRoutersResponse>(
    getPostApiV1SemanticRoutersUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(semanticRouterDefinition),
    },
  );
};

/**
 * List current eligible native Kamelets. With definitionId, include exact historical revisions selected by that saved definition. The current flag identifies current catalog selections.
 * @summary List eligible curated Kamelet actions
 */
export type getApiV1SemanticRoutersActionsResponse200 = {
  data: WanakuResponseListSemanticAction;
  status: 200;
};

export type getApiV1SemanticRoutersActionsResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1SemanticRoutersActionsResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1SemanticRoutersActionsResponseSuccess =
  getApiV1SemanticRoutersActionsResponse200 & {
    headers: Headers;
  };
export type getApiV1SemanticRoutersActionsResponseError = (
  | getApiV1SemanticRoutersActionsResponse400
  | getApiV1SemanticRoutersActionsResponse404
) & {
  headers: Headers;
};

export type getApiV1SemanticRoutersActionsResponse =
  | getApiV1SemanticRoutersActionsResponseSuccess
  | getApiV1SemanticRoutersActionsResponseError;

export const getGetApiV1SemanticRoutersActionsUrl = (
  params?: GetApiV1SemanticRoutersActionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/semantic-routers/actions?${stringifiedParams}`
    : `/api/v1/semantic-routers/actions`;
};

export const getApiV1SemanticRoutersActions = async (
  params?: GetApiV1SemanticRoutersActionsParams,
  options?: RequestInit,
): Promise<getApiV1SemanticRoutersActionsResponse> => {
  return customFetch<getApiV1SemanticRoutersActionsResponse>(
    getGetApiV1SemanticRoutersActionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * List configured expert instances. Publication does not activate a runtime.
 * @summary List configured expert instances
 */
export type getApiV1SemanticRoutersExpertsResponse200 = {
  data: WanakuResponseListSemanticExpert;
  status: 200;
};

export type getApiV1SemanticRoutersExpertsResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1SemanticRoutersExpertsResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1SemanticRoutersExpertsResponseSuccess =
  getApiV1SemanticRoutersExpertsResponse200 & {
    headers: Headers;
  };
export type getApiV1SemanticRoutersExpertsResponseError = (
  | getApiV1SemanticRoutersExpertsResponse400
  | getApiV1SemanticRoutersExpertsResponse404
) & {
  headers: Headers;
};

export type getApiV1SemanticRoutersExpertsResponse =
  | getApiV1SemanticRoutersExpertsResponseSuccess
  | getApiV1SemanticRoutersExpertsResponseError;

export const getGetApiV1SemanticRoutersExpertsUrl = () => {
  return `/api/v1/semantic-routers/experts`;
};

export const getApiV1SemanticRoutersExperts = async (
  options?: RequestInit,
): Promise<getApiV1SemanticRoutersExpertsResponse> => {
  return customFetch<getApiV1SemanticRoutersExpertsResponse>(
    getGetApiV1SemanticRoutersExpertsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Generate all catalog files from a complete draft. The catalog name is semantic-preview and the revision is preview. This operation does not save a draft, publish a catalog, activate a runtime, or call an expert.
 * @summary Inspect generated semantic router files
 */
export type postApiV1SemanticRoutersFilesResponse200 = {
  data: WanakuResponseMapStringString;
  status: 200;
};

export type postApiV1SemanticRoutersFilesResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1SemanticRoutersFilesResponse422 = {
  data: void;
  status: 422;
};

export type postApiV1SemanticRoutersFilesResponseSuccess =
  postApiV1SemanticRoutersFilesResponse200 & {
    headers: Headers;
  };
export type postApiV1SemanticRoutersFilesResponseError = (
  | postApiV1SemanticRoutersFilesResponse400
  | postApiV1SemanticRoutersFilesResponse422
) & {
  headers: Headers;
};

export type postApiV1SemanticRoutersFilesResponse =
  | postApiV1SemanticRoutersFilesResponseSuccess
  | postApiV1SemanticRoutersFilesResponseError;

export const getPostApiV1SemanticRoutersFilesUrl = () => {
  return `/api/v1/semantic-routers/files`;
};

export const postApiV1SemanticRoutersFiles = async (
  semanticRouterDefinition: SemanticRouterDefinition,
  options?: RequestInit,
): Promise<postApiV1SemanticRoutersFilesResponse> => {
  return customFetch<postApiV1SemanticRoutersFilesResponse>(
    getPostApiV1SemanticRoutersFilesUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(semanticRouterDefinition),
    },
  );
};

/**
 * Resolve an exact saved name to immutable publication pins and a published expert snapshot. Draft edits do not select a new publication. An explicit revision overrides the current pointer. Legacy records can omit the expert snapshot.
 * @summary Resolve a published semantic router by name
 */
export type getApiV1SemanticRoutersResolveResponse200 = {
  data: WanakuResponseSemanticResolvedPublication;
  status: 200;
};

export type getApiV1SemanticRoutersResolveResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1SemanticRoutersResolveResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1SemanticRoutersResolveResponse409 = {
  data: void;
  status: 409;
};

export type getApiV1SemanticRoutersResolveResponse500 = {
  data: void;
  status: 500;
};

export type getApiV1SemanticRoutersResolveResponseSuccess =
  getApiV1SemanticRoutersResolveResponse200 & {
    headers: Headers;
  };
export type getApiV1SemanticRoutersResolveResponseError = (
  | getApiV1SemanticRoutersResolveResponse400
  | getApiV1SemanticRoutersResolveResponse404
  | getApiV1SemanticRoutersResolveResponse409
  | getApiV1SemanticRoutersResolveResponse500
) & {
  headers: Headers;
};

export type getApiV1SemanticRoutersResolveResponse =
  | getApiV1SemanticRoutersResolveResponseSuccess
  | getApiV1SemanticRoutersResolveResponseError;

export const getGetApiV1SemanticRoutersResolveUrl = (
  params: GetApiV1SemanticRoutersResolveParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/semantic-routers/resolve?${stringifiedParams}`
    : `/api/v1/semantic-routers/resolve`;
};

export const getApiV1SemanticRoutersResolve = async (
  params: GetApiV1SemanticRoutersResolveParams,
  options?: RequestInit,
): Promise<getApiV1SemanticRoutersResolveResponse> => {
  return customFetch<getApiV1SemanticRoutersResolveResponse>(
    getGetApiV1SemanticRoutersResolveUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Validate configuration without inference. Publication does not activate a runtime.
 * @summary Validate configuration without inference
 */
export type postApiV1SemanticRoutersValidateResponse200 = {
  data: WanakuResponseSemanticValidation;
  status: 200;
};

export type postApiV1SemanticRoutersValidateResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1SemanticRoutersValidateResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1SemanticRoutersValidateResponseSuccess =
  postApiV1SemanticRoutersValidateResponse200 & {
    headers: Headers;
  };
export type postApiV1SemanticRoutersValidateResponseError = (
  | postApiV1SemanticRoutersValidateResponse400
  | postApiV1SemanticRoutersValidateResponse404
) & {
  headers: Headers;
};

export type postApiV1SemanticRoutersValidateResponse =
  | postApiV1SemanticRoutersValidateResponseSuccess
  | postApiV1SemanticRoutersValidateResponseError;

export const getPostApiV1SemanticRoutersValidateUrl = () => {
  return `/api/v1/semantic-routers/validate`;
};

export const postApiV1SemanticRoutersValidate = async (
  semanticRouterDefinition: SemanticRouterDefinition,
  options?: RequestInit,
): Promise<postApiV1SemanticRoutersValidateResponse> => {
  return customFetch<postApiV1SemanticRoutersValidateResponse>(
    getPostApiV1SemanticRoutersValidateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(semanticRouterDefinition),
    },
  );
};

/**
 * Update a router draft. Publication does not activate a runtime.
 * @summary Update a router draft
 */
export type putApiV1SemanticRoutersIdResponse200 = {
  data: WanakuResponseSemanticRouterDefinition;
  status: 200;
};

export type putApiV1SemanticRoutersIdResponse400 = {
  data: void;
  status: 400;
};

export type putApiV1SemanticRoutersIdResponse404 = {
  data: void;
  status: 404;
};

export type putApiV1SemanticRoutersIdResponseSuccess =
  putApiV1SemanticRoutersIdResponse200 & {
    headers: Headers;
  };
export type putApiV1SemanticRoutersIdResponseError = (
  | putApiV1SemanticRoutersIdResponse400
  | putApiV1SemanticRoutersIdResponse404
) & {
  headers: Headers;
};

export type putApiV1SemanticRoutersIdResponse =
  | putApiV1SemanticRoutersIdResponseSuccess
  | putApiV1SemanticRoutersIdResponseError;

export const getPutApiV1SemanticRoutersIdUrl = (id: string) => {
  return `/api/v1/semantic-routers/${id}`;
};

export const putApiV1SemanticRoutersId = async (
  id: string,
  semanticRouterDefinition: SemanticRouterDefinition,
  options?: RequestInit,
): Promise<putApiV1SemanticRoutersIdResponse> => {
  return customFetch<putApiV1SemanticRoutersIdResponse>(
    getPutApiV1SemanticRoutersIdUrl(id),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(semanticRouterDefinition),
    },
  );
};

/**
 * Remove a router draft. Publication does not activate a runtime.
 * @summary Remove a router draft
 */
export type deleteApiV1SemanticRoutersIdResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1SemanticRoutersIdResponse400 = {
  data: void;
  status: 400;
};

export type deleteApiV1SemanticRoutersIdResponse404 = {
  data: void;
  status: 404;
};

export type deleteApiV1SemanticRoutersIdResponseSuccess =
  deleteApiV1SemanticRoutersIdResponse200 & {
    headers: Headers;
  };
export type deleteApiV1SemanticRoutersIdResponseError = (
  | deleteApiV1SemanticRoutersIdResponse400
  | deleteApiV1SemanticRoutersIdResponse404
) & {
  headers: Headers;
};

export type deleteApiV1SemanticRoutersIdResponse =
  | deleteApiV1SemanticRoutersIdResponseSuccess
  | deleteApiV1SemanticRoutersIdResponseError;

export const getDeleteApiV1SemanticRoutersIdUrl = (id: string) => {
  return `/api/v1/semantic-routers/${id}`;
};

export const deleteApiV1SemanticRoutersId = async (
  id: string,
  options?: RequestInit,
): Promise<deleteApiV1SemanticRoutersIdResponse> => {
  return customFetch<deleteApiV1SemanticRoutersIdResponse>(
    getDeleteApiV1SemanticRoutersIdUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * Read a router draft. Publication does not activate a runtime.
 * @summary Read a router draft
 */
export type getApiV1SemanticRoutersIdResponse200 = {
  data: WanakuResponseSemanticRouterDefinition;
  status: 200;
};

export type getApiV1SemanticRoutersIdResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1SemanticRoutersIdResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1SemanticRoutersIdResponseSuccess =
  getApiV1SemanticRoutersIdResponse200 & {
    headers: Headers;
  };
export type getApiV1SemanticRoutersIdResponseError = (
  | getApiV1SemanticRoutersIdResponse400
  | getApiV1SemanticRoutersIdResponse404
) & {
  headers: Headers;
};

export type getApiV1SemanticRoutersIdResponse =
  | getApiV1SemanticRoutersIdResponseSuccess
  | getApiV1SemanticRoutersIdResponseError;

export const getGetApiV1SemanticRoutersIdUrl = (id: string) => {
  return `/api/v1/semantic-routers/${id}`;
};

export const getApiV1SemanticRoutersId = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1SemanticRoutersIdResponse> => {
  return customFetch<getApiV1SemanticRoutersIdResponse>(
    getGetApiV1SemanticRoutersIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Classify without executing actions. Publication does not activate a runtime.
 * @summary Classify without executing actions
 */
export type postApiV1SemanticRoutersIdPreviewResponse200 = {
  data: WanakuResponseSemanticPreview;
  status: 200;
};

export type postApiV1SemanticRoutersIdPreviewResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1SemanticRoutersIdPreviewResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1SemanticRoutersIdPreviewResponse422 = {
  data: void;
  status: 422;
};

export type postApiV1SemanticRoutersIdPreviewResponseSuccess =
  postApiV1SemanticRoutersIdPreviewResponse200 & {
    headers: Headers;
  };
export type postApiV1SemanticRoutersIdPreviewResponseError = (
  | postApiV1SemanticRoutersIdPreviewResponse400
  | postApiV1SemanticRoutersIdPreviewResponse404
  | postApiV1SemanticRoutersIdPreviewResponse422
) & {
  headers: Headers;
};

export type postApiV1SemanticRoutersIdPreviewResponse =
  | postApiV1SemanticRoutersIdPreviewResponseSuccess
  | postApiV1SemanticRoutersIdPreviewResponseError;

export const getPostApiV1SemanticRoutersIdPreviewUrl = (id: string) => {
  return `/api/v1/semantic-routers/${id}/preview`;
};

export const postApiV1SemanticRoutersIdPreview = async (
  id: string,
  semanticPreviewRequest: SemanticPreviewRequest,
  options?: RequestInit,
): Promise<postApiV1SemanticRoutersIdPreviewResponse> => {
  return customFetch<postApiV1SemanticRoutersIdPreviewResponse>(
    getPostApiV1SemanticRoutersIdPreviewUrl(id),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(semanticPreviewRequest),
    },
  );
};

/**
 * Publish an immutable catalog revision. Publication does not activate a runtime.
 * @summary Publish an immutable catalog revision
 */
export type postApiV1SemanticRoutersIdPublishResponse200 = {
  data: WanakuResponseSemanticPublication;
  status: 200;
};

export type postApiV1SemanticRoutersIdPublishResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1SemanticRoutersIdPublishResponse404 = {
  data: void;
  status: 404;
};

export type postApiV1SemanticRoutersIdPublishResponse422 = {
  data: void;
  status: 422;
};

export type postApiV1SemanticRoutersIdPublishResponseSuccess =
  postApiV1SemanticRoutersIdPublishResponse200 & {
    headers: Headers;
  };
export type postApiV1SemanticRoutersIdPublishResponseError = (
  | postApiV1SemanticRoutersIdPublishResponse400
  | postApiV1SemanticRoutersIdPublishResponse404
  | postApiV1SemanticRoutersIdPublishResponse422
) & {
  headers: Headers;
};

export type postApiV1SemanticRoutersIdPublishResponse =
  | postApiV1SemanticRoutersIdPublishResponseSuccess
  | postApiV1SemanticRoutersIdPublishResponseError;

export const getPostApiV1SemanticRoutersIdPublishUrl = (id: string) => {
  return `/api/v1/semantic-routers/${id}/publish`;
};

export const postApiV1SemanticRoutersIdPublish = async (
  id: string,
  options?: RequestInit,
): Promise<postApiV1SemanticRoutersIdPublishResponse> => {
  return customFetch<postApiV1SemanticRoutersIdPublishResponse>(
    getPostApiV1SemanticRoutersIdPublishUrl(id),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * List published revisions. Publication does not activate a runtime.
 * @summary List published revisions
 */
export type getApiV1SemanticRoutersIdRevisionsResponse200 = {
  data: WanakuResponseListSemanticPublication;
  status: 200;
};

export type getApiV1SemanticRoutersIdRevisionsResponse400 = {
  data: void;
  status: 400;
};

export type getApiV1SemanticRoutersIdRevisionsResponse404 = {
  data: void;
  status: 404;
};

export type getApiV1SemanticRoutersIdRevisionsResponseSuccess =
  getApiV1SemanticRoutersIdRevisionsResponse200 & {
    headers: Headers;
  };
export type getApiV1SemanticRoutersIdRevisionsResponseError = (
  | getApiV1SemanticRoutersIdRevisionsResponse400
  | getApiV1SemanticRoutersIdRevisionsResponse404
) & {
  headers: Headers;
};

export type getApiV1SemanticRoutersIdRevisionsResponse =
  | getApiV1SemanticRoutersIdRevisionsResponseSuccess
  | getApiV1SemanticRoutersIdRevisionsResponseError;

export const getGetApiV1SemanticRoutersIdRevisionsUrl = (id: string) => {
  return `/api/v1/semantic-routers/${id}/revisions`;
};

export const getApiV1SemanticRoutersIdRevisions = async (
  id: string,
  options?: RequestInit,
): Promise<getApiV1SemanticRoutersIdRevisionsResponse> => {
  return customFetch<getApiV1SemanticRoutersIdRevisionsResponse>(
    getGetApiV1SemanticRoutersIdRevisionsUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ServiceCatalogResponse200 = {
  data: WanakuResponseListMapStringObject;
  status: 200;
};

export type getApiV1ServiceCatalogResponseSuccess =
  getApiV1ServiceCatalogResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogResponse =
  getApiV1ServiceCatalogResponseSuccess;

export const getGetApiV1ServiceCatalogUrl = (
  params?: GetApiV1ServiceCatalogParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog?${stringifiedParams}`
    : `/api/v1/service-catalog`;
};

export const getApiV1ServiceCatalog = async (
  params?: GetApiV1ServiceCatalogParams,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogResponse> => {
  return customFetch<getApiV1ServiceCatalogResponse>(
    getGetApiV1ServiceCatalogUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deploy
 */
export type postApiV1ServiceCatalogResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceCatalogResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceCatalogResponseSuccess =
  postApiV1ServiceCatalogResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceCatalogResponseError =
  postApiV1ServiceCatalogResponse400 & {
    headers: Headers;
  };

export type postApiV1ServiceCatalogResponse =
  | postApiV1ServiceCatalogResponseSuccess
  | postApiV1ServiceCatalogResponseError;

export const getPostApiV1ServiceCatalogUrl = (
  params?: PostApiV1ServiceCatalogParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog?${stringifiedParams}`
    : `/api/v1/service-catalog`;
};

export const postApiV1ServiceCatalog = async (
  dataStore: DataStore,
  params?: PostApiV1ServiceCatalogParams,
  options?: RequestInit,
): Promise<postApiV1ServiceCatalogResponse> => {
  return customFetch<postApiV1ServiceCatalogResponse>(
    getPostApiV1ServiceCatalogUrl(params),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Download
 */
export type getApiV1ServiceCatalogDownloadResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1ServiceCatalogDownloadResponseSuccess =
  getApiV1ServiceCatalogDownloadResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogDownloadResponse =
  getApiV1ServiceCatalogDownloadResponseSuccess;

export const getGetApiV1ServiceCatalogDownloadUrl = (
  params?: GetApiV1ServiceCatalogDownloadParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog/download?${stringifiedParams}`
    : `/api/v1/service-catalog/download`;
};

export const getApiV1ServiceCatalogDownload = async (
  params?: GetApiV1ServiceCatalogDownloadParams,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogDownloadResponse> => {
  return customFetch<getApiV1ServiceCatalogDownloadResponse>(
    getGetApiV1ServiceCatalogDownloadUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Deployment Instructions
 */
export type getApiV1ServiceCatalogInstructionsResponse200 = {
  data: WanakuResponseDeploymentInstructions;
  status: 200;
};

export type getApiV1ServiceCatalogInstructionsResponseSuccess =
  getApiV1ServiceCatalogInstructionsResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogInstructionsResponse =
  getApiV1ServiceCatalogInstructionsResponseSuccess;

export const getGetApiV1ServiceCatalogInstructionsUrl = (
  params?: GetApiV1ServiceCatalogInstructionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog/instructions?${stringifiedParams}`
    : `/api/v1/service-catalog/instructions`;
};

export const getApiV1ServiceCatalogInstructions = async (
  params?: GetApiV1ServiceCatalogInstructionsParams,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogInstructionsResponse> => {
  return customFetch<getApiV1ServiceCatalogInstructionsResponse>(
    getGetApiV1ServiceCatalogInstructionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Removed
 */
export type getApiV1ServiceCatalogRemovedResponse200 = {
  data: WanakuResponseListMapStringObject;
  status: 200;
};

export type getApiV1ServiceCatalogRemovedResponseSuccess =
  getApiV1ServiceCatalogRemovedResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogRemovedResponse =
  getApiV1ServiceCatalogRemovedResponseSuccess;

export const getGetApiV1ServiceCatalogRemovedUrl = () => {
  return `/api/v1/service-catalog/removed`;
};

export const getApiV1ServiceCatalogRemoved = async (
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogRemovedResponse> => {
  return customFetch<getApiV1ServiceCatalogRemovedResponse>(
    getGetApiV1ServiceCatalogRemovedUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Validate
 */
export type postApiV1ServiceCatalogValidateResponse200 = {
  data: WanakuResponseValidationResult;
  status: 200;
};

export type postApiV1ServiceCatalogValidateResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceCatalogValidateResponse422 = {
  data: void;
  status: 422;
};

export type postApiV1ServiceCatalogValidateResponseSuccess =
  postApiV1ServiceCatalogValidateResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceCatalogValidateResponseError = (
  | postApiV1ServiceCatalogValidateResponse400
  | postApiV1ServiceCatalogValidateResponse422
) & {
  headers: Headers;
};

export type postApiV1ServiceCatalogValidateResponse =
  | postApiV1ServiceCatalogValidateResponseSuccess
  | postApiV1ServiceCatalogValidateResponseError;

export const getPostApiV1ServiceCatalogValidateUrl = () => {
  return `/api/v1/service-catalog/validate`;
};

export const postApiV1ServiceCatalogValidate = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1ServiceCatalogValidateResponse> => {
  return customFetch<postApiV1ServiceCatalogValidateResponse>(
    getPostApiV1ServiceCatalogValidateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ServiceCatalogNameResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1ServiceCatalogNameResponseSuccess =
  deleteApiV1ServiceCatalogNameResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ServiceCatalogNameResponse =
  deleteApiV1ServiceCatalogNameResponseSuccess;

export const getDeleteApiV1ServiceCatalogNameUrl = (name: string) => {
  return `/api/v1/service-catalog/${name}`;
};

export const deleteApiV1ServiceCatalogName = async (
  name: string,
  options?: RequestInit,
): Promise<deleteApiV1ServiceCatalogNameResponse> => {
  return customFetch<deleteApiV1ServiceCatalogNameResponse>(
    getDeleteApiV1ServiceCatalogNameUrl(name),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Get
 */
export type getApiV1ServiceCatalogNameResponse200 = {
  data: WanakuResponseMapStringObject;
  status: 200;
};

export type getApiV1ServiceCatalogNameResponseSuccess =
  getApiV1ServiceCatalogNameResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogNameResponse =
  getApiV1ServiceCatalogNameResponseSuccess;

export const getGetApiV1ServiceCatalogNameUrl = (name: string) => {
  return `/api/v1/service-catalog/${name}`;
};

export const getApiV1ServiceCatalogName = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogNameResponse> => {
  return customFetch<getApiV1ServiceCatalogNameResponse>(
    getGetApiV1ServiceCatalogNameUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Restore
 */
export type postApiV1ServiceCatalogNameRestoreResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceCatalogNameRestoreResponseSuccess =
  postApiV1ServiceCatalogNameRestoreResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceCatalogNameRestoreResponse =
  postApiV1ServiceCatalogNameRestoreResponseSuccess;

export const getPostApiV1ServiceCatalogNameRestoreUrl = (name: string) => {
  return `/api/v1/service-catalog/${name}/restore`;
};

export const postApiV1ServiceCatalogNameRestore = async (
  name: string,
  options?: RequestInit,
): Promise<postApiV1ServiceCatalogNameRestoreResponse> => {
  return customFetch<postApiV1ServiceCatalogNameRestoreResponse>(
    getPostApiV1ServiceCatalogNameRestoreUrl(name),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Versions
 */
export type getApiV1ServiceCatalogNameVersionsResponse200 = {
  data: WanakuResponseListCatalogVersion;
  status: 200;
};

export type getApiV1ServiceCatalogNameVersionsResponseSuccess =
  getApiV1ServiceCatalogNameVersionsResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogNameVersionsResponse =
  getApiV1ServiceCatalogNameVersionsResponseSuccess;

export const getGetApiV1ServiceCatalogNameVersionsUrl = (name: string) => {
  return `/api/v1/service-catalog/${name}/versions`;
};

export const getApiV1ServiceCatalogNameVersions = async (
  name: string,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogNameVersionsResponse> => {
  return customFetch<getApiV1ServiceCatalogNameVersionsResponse>(
    getGetApiV1ServiceCatalogNameVersionsUrl(name),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ServiceCatalogNameVersionsVersionResponse200 = {
  data: WanakuResponseCatalogVersion;
  status: 200;
};

export type getApiV1ServiceCatalogNameVersionsVersionResponseSuccess =
  getApiV1ServiceCatalogNameVersionsVersionResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogNameVersionsVersionResponse =
  getApiV1ServiceCatalogNameVersionsVersionResponseSuccess;

export const getGetApiV1ServiceCatalogNameVersionsVersionUrl = (
  name: string,
  version: number,
) => {
  return `/api/v1/service-catalog/${name}/versions/${version}`;
};

export const getApiV1ServiceCatalogNameVersionsVersion = async (
  name: string,
  version: number,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogNameVersionsVersionResponse> => {
  return customFetch<getApiV1ServiceCatalogNameVersionsVersionResponse>(
    getGetApiV1ServiceCatalogNameVersionsVersionUrl(name, version),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Activate Version
 */
export type postApiV1ServiceCatalogNameVersionsVersionActivateResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceCatalogNameVersionsVersionActivateResponseSuccess =
  postApiV1ServiceCatalogNameVersionsVersionActivateResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceCatalogNameVersionsVersionActivateResponse =
  postApiV1ServiceCatalogNameVersionsVersionActivateResponseSuccess;

export const getPostApiV1ServiceCatalogNameVersionsVersionActivateUrl = (
  name: string,
  version: number,
  params?: PostApiV1ServiceCatalogNameVersionsVersionActivateParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-catalog/${name}/versions/${version}/activate?${stringifiedParams}`
    : `/api/v1/service-catalog/${name}/versions/${version}/activate`;
};

export const postApiV1ServiceCatalogNameVersionsVersionActivate = async (
  name: string,
  version: number,
  params?: PostApiV1ServiceCatalogNameVersionsVersionActivateParams,
  options?: RequestInit,
): Promise<postApiV1ServiceCatalogNameVersionsVersionActivateResponse> => {
  return customFetch<postApiV1ServiceCatalogNameVersionsVersionActivateResponse>(
    getPostApiV1ServiceCatalogNameVersionsVersionActivateUrl(
      name,
      version,
      params,
    ),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Download Version
 */
export type getApiV1ServiceCatalogNameVersionsVersionDownloadResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1ServiceCatalogNameVersionsVersionDownloadResponseSuccess =
  getApiV1ServiceCatalogNameVersionsVersionDownloadResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceCatalogNameVersionsVersionDownloadResponse =
  getApiV1ServiceCatalogNameVersionsVersionDownloadResponseSuccess;

export const getGetApiV1ServiceCatalogNameVersionsVersionDownloadUrl = (
  name: string,
  version: number,
) => {
  return `/api/v1/service-catalog/${name}/versions/${version}/download`;
};

export const getApiV1ServiceCatalogNameVersionsVersionDownload = async (
  name: string,
  version: number,
  options?: RequestInit,
): Promise<getApiV1ServiceCatalogNameVersionsVersionDownloadResponse> => {
  return customFetch<getApiV1ServiceCatalogNameVersionsVersionDownloadResponse>(
    getGetApiV1ServiceCatalogNameVersionsVersionDownloadUrl(name, version),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Deploy
 */
export type postApiV1ServiceTemplateDeployResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceTemplateDeployResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceTemplateDeployResponseSuccess =
  postApiV1ServiceTemplateDeployResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateDeployResponseError =
  postApiV1ServiceTemplateDeployResponse400 & {
    headers: Headers;
  };

export type postApiV1ServiceTemplateDeployResponse =
  | postApiV1ServiceTemplateDeployResponseSuccess
  | postApiV1ServiceTemplateDeployResponseError;

export const getPostApiV1ServiceTemplateDeployUrl = (
  params?: PostApiV1ServiceTemplateDeployParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/deploy?${stringifiedParams}`
    : `/api/v1/service-template/deploy`;
};

export const postApiV1ServiceTemplateDeploy = async (
  dataStore: DataStore,
  params?: PostApiV1ServiceTemplateDeployParams,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateDeployResponse> => {
  return customFetch<postApiV1ServiceTemplateDeployResponse>(
    getPostApiV1ServiceTemplateDeployUrl(params),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Download
 */
export type getApiV1ServiceTemplateDownloadResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1ServiceTemplateDownloadResponseSuccess =
  getApiV1ServiceTemplateDownloadResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateDownloadResponse =
  getApiV1ServiceTemplateDownloadResponseSuccess;

export const getGetApiV1ServiceTemplateDownloadUrl = (
  params?: GetApiV1ServiceTemplateDownloadParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/download?${stringifiedParams}`
    : `/api/v1/service-template/download`;
};

export const getApiV1ServiceTemplateDownload = async (
  params?: GetApiV1ServiceTemplateDownloadParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateDownloadResponse> => {
  return customFetch<getApiV1ServiceTemplateDownloadResponse>(
    getGetApiV1ServiceTemplateDownloadUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get
 */
export type getApiV1ServiceTemplateGetResponse200 = {
  data: WanakuResponseServiceTemplateDetail;
  status: 200;
};

export type getApiV1ServiceTemplateGetResponseSuccess =
  getApiV1ServiceTemplateGetResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateGetResponse =
  getApiV1ServiceTemplateGetResponseSuccess;

export const getGetApiV1ServiceTemplateGetUrl = (
  params?: GetApiV1ServiceTemplateGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/get?${stringifiedParams}`
    : `/api/v1/service-template/get`;
};

export const getApiV1ServiceTemplateGet = async (
  params?: GetApiV1ServiceTemplateGetParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateGetResponse> => {
  return customFetch<getApiV1ServiceTemplateGetResponse>(
    getGetApiV1ServiceTemplateGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Instantiate
 */
export type postApiV1ServiceTemplateInstantiateResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceTemplateInstantiateResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceTemplateInstantiateResponseSuccess =
  postApiV1ServiceTemplateInstantiateResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateInstantiateResponseError =
  postApiV1ServiceTemplateInstantiateResponse400 & {
    headers: Headers;
  };

export type postApiV1ServiceTemplateInstantiateResponse =
  | postApiV1ServiceTemplateInstantiateResponseSuccess
  | postApiV1ServiceTemplateInstantiateResponseError;

export const getPostApiV1ServiceTemplateInstantiateUrl = () => {
  return `/api/v1/service-template/instantiate`;
};

export const postApiV1ServiceTemplateInstantiate = async (
  templateInstantiationRequest: TemplateInstantiationRequest,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateInstantiateResponse> => {
  return customFetch<postApiV1ServiceTemplateInstantiateResponse>(
    getPostApiV1ServiceTemplateInstantiateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(templateInstantiationRequest),
    },
  );
};

/**
 * @summary List
 */
export type getApiV1ServiceTemplateListResponse200 = {
  data: WanakuResponseListServiceTemplateSummary;
  status: 200;
};

export type getApiV1ServiceTemplateListResponseSuccess =
  getApiV1ServiceTemplateListResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateListResponse =
  getApiV1ServiceTemplateListResponseSuccess;

export const getGetApiV1ServiceTemplateListUrl = (
  params?: GetApiV1ServiceTemplateListParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/list?${stringifiedParams}`
    : `/api/v1/service-template/list`;
};

export const getApiV1ServiceTemplateList = async (
  params?: GetApiV1ServiceTemplateListParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateListResponse> => {
  return customFetch<getApiV1ServiceTemplateListResponse>(
    getGetApiV1ServiceTemplateListUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get Properties
 */
export type getApiV1ServiceTemplatePropertiesResponse200 = {
  data: WanakuResponseMapStringMapStringString;
  status: 200;
};

export type getApiV1ServiceTemplatePropertiesResponseSuccess =
  getApiV1ServiceTemplatePropertiesResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplatePropertiesResponse =
  getApiV1ServiceTemplatePropertiesResponseSuccess;

export const getGetApiV1ServiceTemplatePropertiesUrl = (
  params?: GetApiV1ServiceTemplatePropertiesParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/properties?${stringifiedParams}`
    : `/api/v1/service-template/properties`;
};

export const getApiV1ServiceTemplateProperties = async (
  params?: GetApiV1ServiceTemplatePropertiesParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplatePropertiesResponse> => {
  return customFetch<getApiV1ServiceTemplatePropertiesResponse>(
    getGetApiV1ServiceTemplatePropertiesUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Remove
 */
export type deleteApiV1ServiceTemplateRemoveResponse200 = {
  data: WanakuResponseVoid;
  status: 200;
};

export type deleteApiV1ServiceTemplateRemoveResponseSuccess =
  deleteApiV1ServiceTemplateRemoveResponse200 & {
    headers: Headers;
  };
export type deleteApiV1ServiceTemplateRemoveResponse =
  deleteApiV1ServiceTemplateRemoveResponseSuccess;

export const getDeleteApiV1ServiceTemplateRemoveUrl = (
  params?: DeleteApiV1ServiceTemplateRemoveParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/remove?${stringifiedParams}`
    : `/api/v1/service-template/remove`;
};

export const deleteApiV1ServiceTemplateRemove = async (
  params?: DeleteApiV1ServiceTemplateRemoveParams,
  options?: RequestInit,
): Promise<deleteApiV1ServiceTemplateRemoveResponse> => {
  return customFetch<deleteApiV1ServiceTemplateRemoveResponse>(
    getDeleteApiV1ServiceTemplateRemoveUrl(params),
    {
      ...options,
      method: "DELETE",
    },
  );
};

/**
 * @summary Removed
 */
export type getApiV1ServiceTemplateRemovedResponse200 = {
  data: WanakuResponseListMapStringObject;
  status: 200;
};

export type getApiV1ServiceTemplateRemovedResponseSuccess =
  getApiV1ServiceTemplateRemovedResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateRemovedResponse =
  getApiV1ServiceTemplateRemovedResponseSuccess;

export const getGetApiV1ServiceTemplateRemovedUrl = () => {
  return `/api/v1/service-template/removed`;
};

export const getApiV1ServiceTemplateRemoved = async (
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateRemovedResponse> => {
  return customFetch<getApiV1ServiceTemplateRemovedResponse>(
    getGetApiV1ServiceTemplateRemovedUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Restore
 */
export type postApiV1ServiceTemplateRestoreResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceTemplateRestoreResponseSuccess =
  postApiV1ServiceTemplateRestoreResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateRestoreResponse =
  postApiV1ServiceTemplateRestoreResponseSuccess;

export const getPostApiV1ServiceTemplateRestoreUrl = (
  params?: PostApiV1ServiceTemplateRestoreParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/restore?${stringifiedParams}`
    : `/api/v1/service-template/restore`;
};

export const postApiV1ServiceTemplateRestore = async (
  params?: PostApiV1ServiceTemplateRestoreParams,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateRestoreResponse> => {
  return customFetch<postApiV1ServiceTemplateRestoreResponse>(
    getPostApiV1ServiceTemplateRestoreUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Validate
 */
export type postApiV1ServiceTemplateValidateResponse200 = {
  data: WanakuResponseValidationResult;
  status: 200;
};

export type postApiV1ServiceTemplateValidateResponse400 = {
  data: void;
  status: 400;
};

export type postApiV1ServiceTemplateValidateResponse422 = {
  data: void;
  status: 422;
};

export type postApiV1ServiceTemplateValidateResponseSuccess =
  postApiV1ServiceTemplateValidateResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateValidateResponseError = (
  | postApiV1ServiceTemplateValidateResponse400
  | postApiV1ServiceTemplateValidateResponse422
) & {
  headers: Headers;
};

export type postApiV1ServiceTemplateValidateResponse =
  | postApiV1ServiceTemplateValidateResponseSuccess
  | postApiV1ServiceTemplateValidateResponseError;

export const getPostApiV1ServiceTemplateValidateUrl = () => {
  return `/api/v1/service-template/validate`;
};

export const postApiV1ServiceTemplateValidate = async (
  dataStore: DataStore,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateValidateResponse> => {
  return customFetch<postApiV1ServiceTemplateValidateResponse>(
    getPostApiV1ServiceTemplateValidateUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(dataStore),
    },
  );
};

/**
 * @summary Versions
 */
export type getApiV1ServiceTemplateVersionsResponse200 = {
  data: WanakuResponseListCatalogVersion;
  status: 200;
};

export type getApiV1ServiceTemplateVersionsResponseSuccess =
  getApiV1ServiceTemplateVersionsResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateVersionsResponse =
  getApiV1ServiceTemplateVersionsResponseSuccess;

export const getGetApiV1ServiceTemplateVersionsUrl = (
  params?: GetApiV1ServiceTemplateVersionsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/versions?${stringifiedParams}`
    : `/api/v1/service-template/versions`;
};

export const getApiV1ServiceTemplateVersions = async (
  params?: GetApiV1ServiceTemplateVersionsParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateVersionsResponse> => {
  return customFetch<getApiV1ServiceTemplateVersionsResponse>(
    getGetApiV1ServiceTemplateVersionsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Activate Version
 */
export type postApiV1ServiceTemplateVersionsActivateResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type postApiV1ServiceTemplateVersionsActivateResponseSuccess =
  postApiV1ServiceTemplateVersionsActivateResponse200 & {
    headers: Headers;
  };
export type postApiV1ServiceTemplateVersionsActivateResponse =
  postApiV1ServiceTemplateVersionsActivateResponseSuccess;

export const getPostApiV1ServiceTemplateVersionsActivateUrl = (
  params?: PostApiV1ServiceTemplateVersionsActivateParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/versions/activate?${stringifiedParams}`
    : `/api/v1/service-template/versions/activate`;
};

export const postApiV1ServiceTemplateVersionsActivate = async (
  params?: PostApiV1ServiceTemplateVersionsActivateParams,
  options?: RequestInit,
): Promise<postApiV1ServiceTemplateVersionsActivateResponse> => {
  return customFetch<postApiV1ServiceTemplateVersionsActivateResponse>(
    getPostApiV1ServiceTemplateVersionsActivateUrl(params),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Download Version
 */
export type getApiV1ServiceTemplateVersionsDownloadResponse200 = {
  data: WanakuResponseDataStore;
  status: 200;
};

export type getApiV1ServiceTemplateVersionsDownloadResponseSuccess =
  getApiV1ServiceTemplateVersionsDownloadResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateVersionsDownloadResponse =
  getApiV1ServiceTemplateVersionsDownloadResponseSuccess;

export const getGetApiV1ServiceTemplateVersionsDownloadUrl = (
  params?: GetApiV1ServiceTemplateVersionsDownloadParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/versions/download?${stringifiedParams}`
    : `/api/v1/service-template/versions/download`;
};

export const getApiV1ServiceTemplateVersionsDownload = async (
  params?: GetApiV1ServiceTemplateVersionsDownloadParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateVersionsDownloadResponse> => {
  return customFetch<getApiV1ServiceTemplateVersionsDownloadResponse>(
    getGetApiV1ServiceTemplateVersionsDownloadUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Version
 */
export type getApiV1ServiceTemplateVersionsGetResponse200 = {
  data: WanakuResponseCatalogVersion;
  status: 200;
};

export type getApiV1ServiceTemplateVersionsGetResponseSuccess =
  getApiV1ServiceTemplateVersionsGetResponse200 & {
    headers: Headers;
  };
export type getApiV1ServiceTemplateVersionsGetResponse =
  getApiV1ServiceTemplateVersionsGetResponseSuccess;

export const getGetApiV1ServiceTemplateVersionsGetUrl = (
  params?: GetApiV1ServiceTemplateVersionsGetParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/v1/service-template/versions/get?${stringifiedParams}`
    : `/api/v1/service-template/versions/get`;
};

export const getApiV1ServiceTemplateVersionsGet = async (
  params?: GetApiV1ServiceTemplateVersionsGetParams,
  options?: RequestInit,
): Promise<getApiV1ServiceTemplateVersionsGetResponse> => {
  return customFetch<getApiV1ServiceTemplateVersionsGetResponse>(
    getGetApiV1ServiceTemplateVersionsGetUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};
