quarkus.banner.enabled = false
quarkus.devservices.enabled = false

# Authentication Configuration
wanaku.cli.auth.enabled=false
wanaku.cli.auth.mode=none
wanaku.cli.auth.credentials-file=~/.wanaku/credentials

#quarkus.native.resources.includes=nano/**

# Include documentation files in native image
quarkus.native.resources.includes=docs/**

quarkus.log.level=WARNING
quarkus.log.console.stderr=true
quarkus.log.category."ai.wanaku".level=INFO
quarkus.log.category."org.jline".level=ERROR
%dev.quarkus.log.category."ai.wanaku".level=INFO
%test.quarkus.log.category."ai.wanaku".level=INFO
