quarkus.banner.enabled = false
quarkus.devservices.enabled = false

quarkus.log.level=WARNING
quarkus.log.category."ai.wanaku".level=INFO
quarkus.log.category."org.jline".level=ERROR
%dev.quarkus.log.category."ai.wanaku".level=INFO
%test.quarkus.log.category."ai.wanaku".level=INFO
