/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { RedactionMetadata } from "./redactionMetadata";
import type { AuditEventAttributes } from "./auditEventAttributes";

export interface AuditEvent {
  schema_version?: string;
  event_id?: string;
  stream_id?: string;
  sequence?: number;
  category?: string;
  decision?: string;
  correlation_id?: string;
  request_id?: string;
  actor?: string;
  protocol?: string;
  operation?: string;
  target_type?: string;
  target?: string;
  reason_code?: string;
  explanation?: string;
  policy_revision?: string;
  response_status?: number;
  duration_ms?: number;
  redaction?: RedactionMetadata;
  attributes?: AuditEventAttributes;
  coverage_complete?: boolean;
  dropped_events?: number;
  timestamp?: string;
}
