/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { Instant } from "./instant";
import type { DataStoreRecord } from "./dataStoreRecord";
import type { CatalogVersionRecord } from "./catalogVersionRecord";
import type { BarnArchiveVersionCounters } from "./barnArchiveVersionCounters";
import type { AuditEvent } from "./auditEvent";

export interface BarnArchive {
  formatVersion?: number;
  schemaVersion?: number;
  exportedAt?: Instant;
  dataStores?: DataStoreRecord[];
  catalogVersions?: CatalogVersionRecord[];
  versionCounters?: BarnArchiveVersionCounters;
  auditEvents?: AuditEvent[];
  auditSequence?: number;
}
