/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { Instant } from "./instant";
import type { CatalogVersionRecordLabels } from "./catalogVersionRecordLabels";

export interface CatalogVersionRecord {
  type?: string;
  name?: string;
  version?: number;
  status?: string;
  createdAt?: Instant;
  activatedAt?: Instant;
  checksum?: string;
  origin?: string;
  actor?: string;
  failureReason?: string;
  restoredFrom?: number;
  dataStoreName?: string;
  data?: string;
  labels?: CatalogVersionRecordLabels;
  rejected?: boolean;
}
