/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { DataStoreRecordLabels } from "./dataStoreRecordLabels";
import type { Instant } from "./instant";

export interface DataStoreRecord {
  labels?: DataStoreRecordLabels;
  id?: string;
  name?: string;
  data?: string;
  createdAt?: Instant;
  updatedAt?: Instant;
  createdBy?: string;
  updatedBy?: string;
  revision?: number;
}
