/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export type GetApiV1ServiceTemplateListParams = {
  limit?: number;
  offset?: number;
  search?: string;
};
