/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export type GetApiV1AuditEventsParams = {
  actor?: string;
  decision?: string;
  from?: string;
  limit?: number;
  offset?: number;
  operation?: string;
  reason_code?: string;
  target?: string;
  target_type?: string;
  to?: string;
};
