/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export type GetApiV1SemanticRoutersResolveParams = {
  /**
   * @maxLength 120
   * @pattern \S
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 64
   */
  revision?: string;
};
