/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export interface KameletUpload {
  /**
   * Single native Kamelet YAML document, at most 1 MiB in UTF-8 bytes
   * @maxLength 1048576
   * @pattern \S
   */
  yaml: string;
}
