/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Reason this revision is not eligible; null for an eligible action
 */
export type KameletDefinitionSemanticEligibilityReason = string | null;
