/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { KameletDefinitionType } from "./kameletDefinitionType";
import type { KameletDefinitionSemanticEligibilityReason } from "./kameletDefinitionSemanticEligibilityReason";
import type { KameletDefinitionSource } from "./kameletDefinitionSource";

export interface KameletDefinition {
  /** Native Kamelet metadata.name */
  name?: string;
  /** Native definition title */
  title?: string;
  /** Native definition description */
  description?: string;
  /** Native Kamelet type */
  type?: KameletDefinitionType;
  /** SHA-256 of the exact UTF-8 YAML bytes */
  sha256?: string;
  /** Whether this revision is eligible for semantic routing */
  semanticEligible?: boolean;
  /** Reason this revision is not eligible; null for an eligible action */
  semanticEligibilityReason?: KameletDefinitionSemanticEligibilityReason;
  /** Catalog source */
  source?: KameletDefinitionSource;
  /** Whether the current catalog selection can be removed */
  removable?: boolean;
  /** Raw YAML download path pinned to this exact revision */
  downloadUrl?: string;
  /** Original single-document UTF-8 Kamelet YAML, without normalization */
  yaml?: string;
}
