/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Native Kamelet type
 */
export type KameletSummaryType =
  (typeof KameletSummaryType)[keyof typeof KameletSummaryType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KameletSummaryType = {
  source: "source",
  sink: "sink",
  action: "action",
} as const;
