/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { KameletSummaryType } from "./kameletSummaryType";
import type { KameletSummarySemanticEligibilityReason } from "./kameletSummarySemanticEligibilityReason";
import type { KameletSummarySource } from "./kameletSummarySource";

export interface KameletSummary {
  /** Native Kamelet metadata.name */
  name?: string;
  /** Native definition title */
  title?: string;
  /** Native definition description */
  description?: string;
  /** Native Kamelet type */
  type?: KameletSummaryType;
  /** SHA-256 of the exact UTF-8 YAML bytes */
  sha256?: string;
  /** Whether this revision is eligible for semantic routing */
  semanticEligible?: boolean;
  /** Reason this revision is not eligible; null for an eligible action */
  semanticEligibilityReason?: KameletSummarySemanticEligibilityReason;
  /** Catalog source */
  source?: KameletSummarySource;
  /** Whether the current catalog selection can be removed */
  removable?: boolean;
  /** Raw YAML download path pinned to this exact revision */
  downloadUrl?: string;
}
