/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Catalog source
 */
export type KameletDefinitionSource =
  (typeof KameletDefinitionSource)[keyof typeof KameletDefinitionSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const KameletDefinitionSource = {
  bundled: "bundled",
  configured: "configured",
  uploaded: "uploaded",
} as const;
