/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export interface RedactionMetadata {
  redacted_fields?: string[];
  payload_captured?: boolean;
  payload_truncated?: boolean;
}
