/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Only available native confidence and known-label probabilities; no fabricated values
 */
export type SemanticPreviewDiagnostics = { [key: string]: unknown };
