/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticExpert } from "./semanticExpert";

/**
 * Published expert snapshot; absent when a legacy archive cannot prove one unique curated expert
 */
export type SemanticResolvedPublicationExpertAnyOf = SemanticExpert | null;
