/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticActionType } from "./semanticActionType";
import type { SemanticActionInputSchema } from "./semanticActionInputSchema";
import type { SemanticActionOutputSchema } from "./semanticActionOutputSchema";
import type { SemanticActionConfigurationSchema } from "./semanticActionConfigurationSchema";

export interface SemanticAction {
  /** Native metadata.name used as the Kamelet identifier */
  id?: string;
  /** SHA-256 pin for the exact selected native Kamelet bytes; omitted on legacy selections */
  sha256?: string;
  /** Whether this action revision is the current catalog selection */
  current?: boolean;
  /** Native Kamelet type; sinks return a fixed acknowledgement after successful delivery */
  type?: SemanticActionType;
  /** Native Kamelet title */
  name?: string;
  /** Native Kamelet purpose */
  description?: string;
  /** Suggested native routing criterion */
  criteria?: string;
  /** Compatible invocation and result profile */
  profile?: string;
  /** Native Kamelet input body schema */
  inputSchema?: SemanticActionInputSchema;
  /** Native Kamelet output body schema */
  outputSchema?: SemanticActionOutputSchema;
  /** Native deployment configuration JSON Schema; secret fields accept external references only */
  configurationSchema?: SemanticActionConfigurationSchema;
  /** Native Kamelet implementation dependencies */
  dependencies?: string[];
}
