/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Deployment parameter values; credentials use env:VARIABLE_NAME references
 */
export type SemanticActionSelectionConfiguration = { [key: string]: string };
