/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticPreviewLabel } from "./semanticPreviewLabel";
import type { SemanticPreviewError } from "./semanticPreviewError";
import type { SemanticPreviewDiagnostics } from "./semanticPreviewDiagnostics";

export interface SemanticPreview {
  /** Selected fixed action label, or no_match; null on evaluation failure */
  label?: SemanticPreviewLabel;
  /** True only for the explicit no_match label */
  noMatch?: boolean;
  /** Evaluation wall-clock duration in milliseconds */
  durationMillis?: number;
  /** Sanitized evaluation error; null after successful classification */
  error?: SemanticPreviewError;
  /** Only available native confidence and known-label probabilities; no fabricated values */
  diagnostics?: SemanticPreviewDiagnostics;
}
