/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Native deployment configuration JSON Schema; secret fields accept external references only
 */
export type SemanticActionConfigurationSchema = { [key: string]: unknown };
