/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Sanitized evaluation error; null after successful classification
 */
export type SemanticPreviewError = string | null;
