/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticPublicationToolName } from "./semanticPublicationToolName";
import type { SemanticPublicationExpert } from "./semanticPublicationExpert";
import type { SemanticPublicationCamelBuild } from "./semanticPublicationCamelBuild";

export interface SemanticPublication {
  /** Persisted authoring definition identifier */
  definitionId?: string;
  /** Public MCP tool name captured at publication; absent in legacy records */
  toolName?: SemanticPublicationToolName;
  /** Expert identity and implementation captured at publication without credentials; absent in legacy records */
  expert?: SemanticPublicationExpert;
  /** Immutable revision derived from the generated catalog inputs */
  revision?: string;
  /** Revision-specific existing Barn catalog name */
  catalogName?: string;
  /** SHA-256 pin for the complete downloaded ZIP archive */
  sha256?: string;
  /** Main Camel YAML path inside the archive */
  mainFile?: string;
  /** Required Camel runtime version */
  camelVersion?: string;
  /** Required fixed Camel snapshot timestamp when recorded */
  camelBuild?: SemanticPublicationCamelBuild;
  /** Existing Barn catalog download path returning a Base64 ZIP */
  downloadUrl?: string;
  /** Instructions to select and start this revision in WSR */
  deploymentInstructions?: string[];
  /** Publication state; does not assert runtime readiness or activation */
  status?: string;
}
