/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Native Kamelet type; sinks return a fixed acknowledgement after successful delivery
 */
export type SemanticActionType =
  (typeof SemanticActionType)[keyof typeof SemanticActionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SemanticActionType = {
  action: "action",
  sink: "sink",
} as const;
