/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export interface SemanticExpert {
  /** Configured expert catalog identifier */
  id?: string;
  /** Configured expert display name */
  name?: string;
  /** Named Camel expert instance configured externally by the deployment */
  bean?: string;
  /** Maven group:artifact:version implementation dependency */
  dependency?: string;
  /** Whether this contract exposes confidence controls */
  supportsConfidence?: boolean;
}
