/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticActionSelectionConfiguration } from "./semanticActionSelectionConfiguration";

export interface SemanticActionSelection {
  /** Eligible native Kamelet identifier */
  actionId?: string;
  /** SHA-256 pin for the exact selected native Kamelet bytes; omitted on legacy selections */
  sha256?: string;
  /** Fixed unique semantic label; no_match is reserved */
  label?: string;
  /** Plain text criterion for selecting this action */
  criteria?: string;
  /** Deployment parameter values; credentials use env:VARIABLE_NAME references */
  configuration?: SemanticActionSelectionConfiguration;
}
