/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Selected fixed action label, or no_match; null on evaluation failure
 */
export type SemanticPreviewLabel = string | null;
