/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Public MCP tool name captured at publication; absent in legacy records
 */
export type SemanticPublicationToolName = string | null;
