/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticActionSelection } from "./semanticActionSelection";
import type { SemanticExample } from "./semanticExample";

export interface SemanticRouterDefinition {
  /** Persisted draft identifier, assigned by Barn */
  id?: string;
  /**
   * Router name; start with an ASCII letter, then use ASCII letters, digits, hyphens, or underscores; no spaces; at most 120 characters; empty for an incomplete draft
   * @maxLength 120
   * @pattern ^([A-Za-z][A-Za-z0-9_-]*)?$
   */
  name?: string;
  /** Business purpose and public MCP tool description */
  description?: string;
  /**
   * Public MCP tool name; start with an ASCII letter, then use ASCII letters, digits, hyphens, or underscores; no spaces; at most 64 characters; empty for an incomplete draft
   * @maxLength 64
   * @pattern ^([A-Za-z][A-Za-z0-9_-]*)?$
   */
  toolName?: string;
  /** Supported action input and output profile */
  profile?: string;
  /** Configured expert catalog identifier */
  expertId?: string;
  /** Invocation field supplied to native semantic evaluation */
  semanticInput?: string;
  /** Plain text instructions for native choice evaluation */
  instructions?: string;
  /** Criterion for the reserved no_match label */
  noMatchCriteria?: string;
  /** Fixed eligible actions with deployment configuration and selection criteria */
  actions?: SemanticActionSelection[];
  /** Saved classification examples and expected labels */
  examples?: SemanticExample[];
}
