/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

export interface SemanticPreviewRequest {
  /**
   * Example invocation message to classify without action dispatch
   * @maxLength 8192
   * @pattern \S
   */
  message: string;
}
