/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticPublicationExpertAnyOf } from "./semanticPublicationExpertAnyOf";

/**
 * Expert identity and implementation captured at publication without credentials; absent in legacy records
 */
export type SemanticPublicationExpert = SemanticPublicationExpertAnyOf | null;
