/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticResolvedPublicationCamelBuild } from "./semanticResolvedPublicationCamelBuild";
import type { SemanticResolvedPublicationExpert } from "./semanticResolvedPublicationExpert";

export interface SemanticResolvedPublication {
  /** Exact current saved router name used for lookup */
  name?: string;
  /** Public MCP tool name in the selected immutable archive */
  toolName?: string;
  /** Revision-specific Barn catalog index name */
  catalogName?: string;
  /** Selected service identifier in the catalog index */
  service?: string;
  /** Immutable published revision */
  revision?: string;
  /** SHA-256 pin for the complete downloaded ZIP */
  sha256?: string;
  /** Main Camel YAML path inside the archive */
  mainFile?: string;
  /** Required Camel runtime version */
  camelVersion?: string;
  /** Required fixed Camel snapshot timestamp when recorded */
  camelBuild?: SemanticResolvedPublicationCamelBuild;
  /** Existing Barn catalog download path returning a Base64 ZIP */
  downloadUrl?: string;
  /** Published expert snapshot; absent when a legacy archive cannot prove one unique curated expert */
  expert?: SemanticResolvedPublicationExpert;
}
