/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */

/**
 * Required fixed Camel snapshot timestamp when recorded
 */
export type SemanticResolvedPublicationCamelBuild = string | null;
