/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { SemanticFieldError } from "./semanticFieldError";

export interface SemanticValidation {
  /** True when all structural checks pass without inference */
  valid?: boolean;
  /** Structural field errors; empty for a valid definition */
  errors?: SemanticFieldError[];
}
