/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { ValidationIssue } from "./validationIssue";

export interface ValidationResult {
  type?: string;
  name?: string;
  valid?: boolean;
  errors?: ValidationIssue[];
  warnings?: ValidationIssue[];
}
