/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { KameletSummary } from "./kameletSummary";

export interface WanakuResponseListKameletSummary {
  error?: WanakuError;
  data?: KameletSummary[];
}
