/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * wanaku-barn-backend API
 * OpenAPI spec version: 0.3.0-SNAPSHOT
 */
import type { WanakuError } from "./wanakuError";
import type { AuditEvent } from "./auditEvent";

export interface WanakuResponseAuditEvent {
  error?: WanakuError;
  data?: AuditEvent;
}
