---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Release.Namespace }}-wanaku-service-catalog-cluster-role
rules:
  - apiGroups:
      - wanaku.ai
    resources:
      - wanakuservicecatalogs
      - wanakuservicecatalogs/status
      - wanakuservicecatalogs/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Release.Namespace }}-wanaku-router-cluster-role
rules:
  - apiGroups:
      - wanaku.ai
    resources:
      - wanakurouters
      - wanakurouters/status
      - wanakurouters/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - services
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  name: {{ .Release.Namespace }}-josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
