---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.33.2
  labels:
    app.kubernetes.io/name: wanaku-operator
    app.kubernetes.io/managed-by: quarkus
  name: wanaku-operator
  namespace: {{ .Release.Namespace }}
