---
openapi: 3.1.0
components:
  schemas:
    DataStore:
      type: object
      properties:
        labels:
          type: object
          additionalProperties:
            type: string
        id:
          type: string
        name:
          type: string
        data:
          type: string
    DeploymentInstructions:
      type: object
      properties:
        catalogName:
          type: string
        catalogType:
          type: string
        deploymentModel:
          type: string
        systems:
          type: array
          items:
            $ref: "#/components/schemas/SystemInstruction"
        placeholders:
          type: array
          items:
            $ref: "#/components/schemas/PlaceholderDefinition"
    PlaceholderDefinition:
      type: object
      properties:
        key:
          type: string
        label:
          type: string
        description:
          type: string
        defaultValue:
          type: string
        type:
          type: string
    ServerInfo:
      type: object
      properties:
        version:
          type: string
    ServiceTemplateDetail:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        icon:
          type: string
        description:
          type: string
        services:
          type: array
          items:
            $ref: "#/components/schemas/ServiceTemplateSystem"
    ServiceTemplateSummary:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        icon:
          type: string
        description:
          type: string
        services:
          type: array
          items:
            type: string
        hasProperties:
          type: boolean
    ServiceTemplateSystem:
      type: object
      properties:
        name:
          type: string
        routesFile:
          type: string
        rulesFile:
          type: string
        dependenciesFile:
          type: string
        propertiesFile:
          type: string
    SystemInstruction:
      type: object
      properties:
        systemName:
          type: string
        instruction:
          type: string
        format:
          type: string
    SystemStatistics:
      type: object
      properties:
        serviceCatalogsCount:
          type: integer
          format: int64
        serviceTemplatesCount:
          type: integer
          format: int64
        dataStoresCount:
          type: integer
          format: int64
    TemplateInstantiationRequest:
      type: object
      properties:
        templateName:
          type: string
        properties:
          type: object
          additionalProperties:
            type: string
        serviceName:
          type: string
        serviceSystem:
          type: string
    WanakuError:
      type: object
      properties:
        message:
          type: string
    WanakuResponse:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data: {}
    WanakuResponseDataStore:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          $ref: "#/components/schemas/DataStore"
    WanakuResponseDeploymentInstructions:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          $ref: "#/components/schemas/DeploymentInstructions"
    WanakuResponseInteger:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          type: integer
          format: int32
    WanakuResponseListDataStore:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          type: array
          items:
            $ref: "#/components/schemas/DataStore"
    WanakuResponseListMapStringObject:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          type: array
          items:
            type: object
            additionalProperties: {}
    WanakuResponseListServiceTemplateSummary:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          type: array
          items:
            $ref: "#/components/schemas/ServiceTemplateSummary"
    WanakuResponseMapStringMapStringString:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          type: object
          additionalProperties:
            type: object
            additionalProperties:
              type: string
    WanakuResponseMapStringObject:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          type: object
          additionalProperties: {}
    WanakuResponseServerInfo:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          $ref: "#/components/schemas/ServerInfo"
    WanakuResponseServiceTemplateDetail:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          $ref: "#/components/schemas/ServiceTemplateDetail"
    WanakuResponseSystemStatistics:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data:
          $ref: "#/components/schemas/SystemStatistics"
    WanakuResponseVoid:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/WanakuError"
        data: {}
paths:
  /api/v1/data-store:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataStore"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseVoid"
        "400":
          description: Bad Request
      summary: Update
      tags:
      - Data Stores Resource
    delete:
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseVoid"
      summary: Remove By Name
      tags:
      - Data Stores Resource
    get:
      parameters:
      - name: labelFilter
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseListDataStore"
      summary: List Or Get By Name
      tags:
      - Data Stores Resource
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataStore"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
        "400":
          description: Bad Request
      summary: Add
      tags:
      - Data Stores Resource
  /api/v1/data-store/labels:
    delete:
      parameters:
      - name: labelExpression
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseInteger"
      summary: Remove If
      tags:
      - Data Stores Resource
  /api/v1/data-store/{id}:
    delete:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseVoid"
      summary: Remove By Id
      tags:
      - Data Stores Resource
    get:
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
      summary: Get By Id
      tags:
      - Data Stores Resource
  /api/v1/management/info/version:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseServerInfo"
      summary: Version
      tags:
      - Info Resource
  /api/v1/management/statistics:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseSystemStatistics"
      summary: Get Statistics
      tags:
      - Statistics Resource
  /api/v1/service-catalog:
    get:
      parameters:
      - name: search
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseListMapStringObject"
      summary: List
      tags:
      - Service Catalog Resource
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataStore"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
        "400":
          description: Bad Request
      summary: Deploy
      tags:
      - Service Catalog Resource
  /api/v1/service-catalog/download:
    get:
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
      summary: Download
      tags:
      - Service Catalog Resource
  /api/v1/service-catalog/instructions:
    get:
      parameters:
      - name: model
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDeploymentInstructions"
      summary: Get Deployment Instructions
      tags:
      - Service Catalog Resource
  /api/v1/service-catalog/{name}:
    delete:
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseVoid"
      summary: Remove
      tags:
      - Service Catalog Resource
    get:
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseMapStringObject"
      summary: Get
      tags:
      - Service Catalog Resource
  /api/v1/service-template/deploy:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DataStore"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
        "400":
          description: Bad Request
      summary: Deploy
      tags:
      - Service Template Resource
  /api/v1/service-template/download:
    get:
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
      summary: Download
      tags:
      - Service Template Resource
  /api/v1/service-template/get:
    get:
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseServiceTemplateDetail"
      summary: Get
      tags:
      - Service Template Resource
  /api/v1/service-template/instantiate:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TemplateInstantiationRequest"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseDataStore"
        "400":
          description: Bad Request
      summary: Instantiate
      tags:
      - Service Template Resource
  /api/v1/service-template/list:
    get:
      parameters:
      - name: search
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseListServiceTemplateSummary"
      summary: List
      tags:
      - Service Template Resource
  /api/v1/service-template/properties:
    get:
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseMapStringMapStringString"
      summary: Get Properties
      tags:
      - Service Template Resource
  /api/v1/service-template/remove:
    delete:
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WanakuResponseVoid"
      summary: Remove
      tags:
      - Service Template Resource
info:
  title: wanaku-barn-backend API
  version: 0.3.0-SNAPSHOT
servers:
- url: http://localhost:8180
  description: Auto generated value
- url: http://0.0.0.0:8180
  description: Auto generated value
