services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"

  jaeger:
    image: jaegertracing/jaeger:latest
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"

  wanaku-router:
    image: quay.io/wanaku/wanaku-barn-backend:latest
    environment:
      QUARKUS_HTTP_HOST: 0.0.0.0
      QUARKUS_OTEL_SDK_DISABLED: "false"
      QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: http://localhost:4317
    network_mode: host
    volumes:
      - wanaku-router:/home/jboss/.wanaku/barn
    healthcheck:
      test: curl -f localhost:8080/api/v1/management/info/version || exit 1
      interval: 10s
      timeout: 10s
      retries: 5

  wanaku-praxis:
    image: quay.io/wanaku/wanaku-praxis:latest
    environment:
      WANAKU_CLASSIC_URL: http://localhost:8080
      WANAKU_MGMT_LISTEN: 0.0.0.0:9090
      WANAKU_PERSIST_BACKEND: file
      WANAKU_PERSIST_PATH: /data/registry
    network_mode: host
    volumes:
      - wanaku-praxis:/data/registry
    depends_on:
      wanaku-router:
        condition: service_healthy
    healthcheck:
      test: curl -f localhost:9090/healthz || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  wanaku-router:
  wanaku-praxis:
